# Generated by Django 6.1.1 on 2026-09-07 03:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('is_closed', models.BooleanField(default=False)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('cached_total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cached_total_meals', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('cached_meal_rate', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='months', to='groups.group')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('group', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='DailyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('lunch', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('dinner', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mess_entries', to=settings.AUTH_USER_MODEL)),
                ('month_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='mess.monthcycle')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('month_cycle', 'user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('month_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='mess.monthcycle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('month_cycle', 'user')},
            },
        ),
    ]
